.PHONY: clean stats test


stats:
	javac PercolationStats.java Percolation.java
	java PercolationStats


test:
	javac PercolationTest.java Percolation.java WeightedQuickUnionUF.java
	java PercolationTest


clean:
	rm -rf *.class
